on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        ftp-server: ftp.codexsolutions.co.ke
        ftp-username: moringa@codexsolutions.co.ke
        ftp-password: ${{ secrets.FTP_PASSWORD }}